### ISSUE TITLE
Version 2.2.0 doesn't work with Tampermonkey

### ISSUE THREAD

**Issue by Gazir** [RaitaroH/YouTube-DeepDark#4]
Earlier versions worked but 2.2.0 doesn't work at all. I use userscript from userstyles, Classic version.

**Comment by RaitaroH** [comment]
Let me guess... Tampermonkey?
Tampermonkey DOES NOT understand the regexp I used for the theme in order to exclude youtube gaming from the theme. I DO NOT write JS code for the userscript. I only write the CSS code. userstyles.org automatically generates the JS script. Greasemonkey and Violentmonkey work well. Tampermonkey for some reason doesn't.

There is nothing I can do about it.

**Comment by Gazir** [comment]
Yes, Tampermonkey. Ok then, can I change that exclusion somehow. I don't use gaming.youtube.com, if you ask. If it's too complicated than nothing, don't bother. Thank you for the best dark theme for YouTube anyway.

**Comment by MechaLynx** [comment]
@Gazir You can change the exclusion by turning it back to `domain(youtube.com)` from `regexp('https?:\/\/(?!gaming\.).*youtube\.com\/.*')`.

The thing is, this is a Tampermonkey bug so there's nothing we can directly do about it and since it's _only_ Tampermonkey, we've decided to ignore that instead of reverting the style, which is what we'd have to do. It's a question of either breaking `gaming.youtube.com` or breaking Tampermonkey and we decided it was better to break the userscript version that's running on one of the engines (some users) rather than break `gaming.youtube.com` which would apply to all versions (all users).

In any case, Violentmonkey and Greasemonkey work fine. I think Violentmonkey works pretty much like Tampermonkey does and is available on Chrome as well. If switching userscript engines is too much, perhaps consider using the userstyle version (the userscript is generated by `userstyles.org`, not us) through Stylus (or Stylish if you're on Firefox 56).

**Comment by RaitaroH** [comment]
I've opened an issue on the tampermonkey github page [here](https://github.com/Tampermonkey/tampermonkey/issues/467).

**Comment by Gazir** [comment]
@MechaLynx Doesn't work. Tampermonkey says there is no include information, whatever that means.

**Comment by MechaLynx** [comment]
@Gazir That was for the included style - it's the quoted string.

If you want to fix it using the userscript header, just add `// @include www.youtube.com/*` at the top. I think you can also edit the includes separately with Tampermonkey but I don't have it in front of me at the moment.

**Comment by Gazir** [comment]
I understand for `// @include` in userscript header but I don't understand what exactly I need to change from first 3 lines of code?

````
(function() {var css = "";
if (false || (new RegExp("^https?://(?!gaming.).*youtube.com/.*$")).test(document.location.href) || (document.domain == "apis.google.com" || document.domain.substring(document.domain.indexOf(".apis.google.com") + 1) == "apis.google.com"))
	css += [
````

**Comment by MechaLynx** [comment]
@Gazir because that's what Tampermonkey and other userscript engines use to detect which sites to run the script on. Since userstyles.org doesn't add `// @include`, the extension needs to figure it out by itself and that's what it looks at.

Since the javascript file from userstyles.org is pre-generated, no matter what you change, it'll go back to how it was on every update.

**Comment by Gazir** [comment]
I know that update will change everything but I just want to remove exclusion (RegExp). What I need to change? Is it even possible?

**Comment by MechaLynx** [comment]
I just tested it. Add this to the metadata of the userscript:

```
// @include       https://www.youtube.com/*
// @include       http://www.youtube.com/*
```

There's no need to change anything else.

**Comment by RaitaroH** [comment]
Even  `// @include       *` can be enough.

**Comment by MechaLynx** [comment]
Then Tampermonkey will inject it on every website, which will be slow and could mess things up. No need to be _that_ lazy :P

**Comment by RaitaroH** [comment]
I just hope that tampermonkey is going to be fixed. Until then we will have to go with what we can.

**Comment by Gazir** [comment]
@MechaLynx Thank you, works now.

**Comment by RaitaroH** [comment]
Tampermonkey most likely will not be fixed. Userstyles will most likely not change their code creation either.
Untill then this theme will not work with Tampermonkey.

**Comment by RaitaroH** [comment]
@Gazir Tampermonkey got fixed btw.

**Comment by lnorton89** [comment]
Still get "invalid userscript" from tampermonkey on opera trying to use this.

**Comment by RaitaroH** [comment]
@lnorton89 I cannot help you more than the thread itself. This theme is a css only theme made for stylus in particular. If you have troubles with Tampermonkey please open an issue/comment on that github page, not here.

**Comment by lnorton89** [comment]
Gotcha, may be pertinent to add this info to the readme for people that have zero idea what Stylus is.
