### ISSUE TITLE
No theme for Youtube Studio

### ISSUE THREAD

**Issue by apathy** [RaitaroH/YouTube-DeepDark#56]
Hey, while installing the theme I could see the regex does have 'studio' in it but not sure if this was ever meant to work there, if not I'll probably make it work there and create a pull request. Thanks for the great theme!

**Comment by RaitaroH** [comment]
Hello @apathy. You are welcome! Regarding theming the studio, I will not theme it.

I didn't theme the Studio and I will not for a few reasons:

1. the studio was in a transition period so theming it then would have been pointless then, but I never came back to it
2. I don't use the studio so I will not notice any problems when they show up
3. because I don't have youtube videos myself, a lot of things in the studio I will never see, thus my theme will be incomplete
4. I already have things that brake in other places and I don't notice for a while, I don't need the studio to do that too :)
